repos:
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
    - id: black
      language_version: python3
      args:
        - "--preview"
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black"]
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: 
          - "--max-line-length=88"
          - "--ignore=E203,W503"
        exclude: docs
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.960'
    hooks:
      - id: mypy
